export const ROUTE_PATH = {
  root: "/",
  login: "/login",
  singup: "/signup",
  product: "/product",
  order: "/order",
  cart: "/cart",
  account: "/account",
  search: "/search",
  categoryList: "/categoryList/:id",
  productDetail: "/api/admin/productDetail/:id",
  inbox: "/inbox",
  PopularProduct: "/popularProduct",
  about_us: "/about_us",
  term: "/term",
  checkout: "/checkout",
};
export const ROUTE_API = {
  root: process.env.REACT_APP_API_URL,
  login: "/api/auth/login",
  register: "/api/auth/signup",
  listProduct: "/api/products",
  listCategory: "/api/categories",
  pularProduct: "/api/products/popular",
  listOrder: "/api/orders/userOrder",
  listNotification: "/api/notification",
  updateNotification: "/api/notification/:id/read",
  listProductPromote: "/api/promotions/promotion-products",
  userOrdered: "/api/orders/user/:userId",
  createOrder: "/api/orders",
  cancelOrder: "/api/orders/:orderId",
};
